---
- name: Install ruby dependencies
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - build-essential
  sudo: True

# Install correct version of ruby from source
- name: ruby-from-src | ensure directory temporary ruby download directory is present
  file: state=directory path=$rubyTmpDir

- name: ruby-from-src | Download ruby source 
  get_url:
    url: "{{ rubyUrl }}"
    dest: "{{ rubyTmpDir }}"
    sha256sum: "{{ rubySHA256 }}"
  sudo: True

- name: ruby-from-src | ensure ruby is extracted
  command: tar -xf {{ rubyCompressedFile }} chdir={{ rubyTmpDir }} creates={{ tmpRubyPath }}
  sudo: True

- name: ruby-from-src | ensure ruby is configured
  command: ./configure chdir={{ tmpRubyPath }} creates={{ tmpRubyPath }}/Makefile
  sudo: True

- name: ruby-from-src | ensure ruby is compiled
  command: make chdir={{ tmpRubyPath }} creates={{ tmpRubyPath }}/ruby
  sudo: True

- name: ruby-from-src | ensure ruby is installed
  command: make install chdir={{ tmpRubyPath }} creates=/usr/local/bin/ruby
  sudo: True
